# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_deployment_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.14

      - name: Install the AaC Package
        run: pip install -e .[test]

      - name: Lint with flake8
        run: flake8 .

      - name: Run Tox Tests With Coverage
        run: tox -e py310

      - name: Build distribution
        run: |
          python -m build
        working-directory: ${{ github.workspace }}

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: aac_req_qa_wheel
          path: dist/
  
  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-22.04
    needs: build_deployment_artifacts
    permissions:
      # Important:  This permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Download Python Wheel
        uses: actions/download-artifact@v4
        with:
          name: aac_req_qa_wheel
          path: dist/
  
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
